import requests

# 1️⃣ URL of your running backend
URL = "http://127.0.0.1:8000/predict/"

# 2️⃣ Full feature order with example values
test_input = {
    'Destination Port': 80,
    'Flow Duration': 500,
    'Total Fwd Packets': 5,
    'Total Backward Packets': 3,
    'Total Length of Fwd Packets': 600,
    'Total Length of Bwd Packets': 300,
    'Fwd Packet Length Max': 200,
    'Fwd Packet Length Min': 50,
    'Fwd Packet Length Mean': 120,
    'Fwd Packet Length Std': 30,
    'Bwd Packet Length Max': 180,
    'Bwd Packet Length Min': 40,
    'Bwd Packet Length Mean': 100,
    'Bwd Packet Length Std': 25,
    'Flow Bytes/s': 1500,
    'Flow Packets/s': 8,
    'Flow IAT Mean': 15,
    'Flow IAT Std': 5,
    'Flow IAT Max': 30,
    'Flow IAT Min': 1,
    'Fwd IAT Total': 50,
    'Fwd IAT Mean': 10,
    'Fwd IAT Std': 2,
    'Fwd IAT Max': 15,
    'Fwd IAT Min': 5,
    'Bwd IAT Total': 40,
    'Bwd IAT Mean': 8,
    'Bwd IAT Std': 1,
    'Bwd IAT Max': 12,
    'Bwd IAT Min': 4,
    'Fwd PSH Flags': 0,
    'Bwd PSH Flags': 0,
    'Fwd URG Flags': 0,
    'Bwd URG Flags': 0,
    'Fwd Header Length': 60,
    'Bwd Header Length': 60,
    'Fwd Packets/s': 5,
    'Bwd Packets/s': 3,
    'Min Packet Length': 50,
    'Max Packet Length': 200,
    'Packet Length Mean': 120,
    'Packet Length Std': 30,
    'Packet Length Variance': 400,
    'FIN Flag Count': 0,
    'SYN Flag Count': 1,
    'RST Flag Count': 0,
    'PSH Flag Count': 0,
    'ACK Flag Count': 1,
    'URG Flag Count': 0,
    'CWE Flag Count': 0,
    'ECE Flag Count': 0,
    'Down/Up Ratio': 1,
    'Average Packet Size': 75,
    'Avg Fwd Segment Size': 60,
    'Avg Bwd Segment Size': 50,
    'Fwd Header Length.1': 60,
    'Fwd Avg Bytes/Bulk': 0,
    'Fwd Avg Packets/Bulk': 0,
    'Fwd Avg Bulk Rate': 0,
    'Bwd Avg Bytes/Bulk': 0,
    'Bwd Avg Packets/Bulk': 0,
    'Bwd Avg Bulk Rate': 0,
    'Subflow Fwd Packets': 2,
    'Subflow Fwd Bytes': 100,
    'Subflow Bwd Packets': 2,
    'Subflow Bwd Bytes': 80,
    'Init_Win_bytes_forward': 65535,
    'Init_Win_bytes_backward': 65535,
    'act_data_pkt_fwd': 0,
    'min_seg_size_forward': 0,
    'Active Mean': 0,
    'Active Std': 0,
    'Active Max': 0,
    'Active Min': 0,
    'Idle Mean': 0,
    'Idle Std': 0,
    'Idle Max': 0,
    'Idle Min': 0
}

# 3️⃣ Send POST request
response = requests.post(URL, json=test_input)

# 4️⃣ Print response
print("Response from backend:")
print(response.json())